version: '3.5'

volumes:
  data:

services:
  database:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  pyspark:
    build:
      context: .
      dockerfile: Dockerfile
    #environment:
    #  - JAVA_HOME=/opt/java/jdk-17.0.9
    #  - PATH=$PATH:$JAVA_HOME/bin
    container_name: pyspark
    ports:
      - "8888:8888"
    volumes:
      - ./pyspark_data:/data

    command: tail -f /dev/null

