version: '3.5'

volumes:
  data:

services:
  pyspark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyspark
    ports:
      - "8888:8888"

    command: tail -f /dev/null
